In [ ]:
import numpy as np
import sympy as sym


In [ ]:
t1 = sym.Symbol('t1')
t2 = sym.Symbol('t2')
t3 = sym.Symbol('t3')
t4 = sym.Symbol('t4')
t5 = sym.Symbol('t5')
t6 = sym.Symbol('t6')
t7 = sym.Symbol('t7')

td1 = sym.Symbol('td1')
td2 = sym.Symbol('td2')
td3 = sym.Symbol('td3')
td4 = sym.Symbol('td4')
td5 = sym.Symbol('td5')
td6 = sym.Symbol('td6')
td7 = sym.Symbol('td7')


tdd1 = sym.Symbol('tdd1')
tdd2 = sym.Symbol('tdd2')
tdd3 = sym.Symbol('tdd3')
tdd4 = sym.Symbol('tdd4')
tdd5 = sym.Symbol('tdd5')
tdd6 = sym.Symbol('tdd6')
tdd7 = sym.Symbol('tdd7')


c1 = sym.Symbol('c1')
c2 = sym.Symbol('c2')
c3 = sym.Symbol('c3')
c4 = sym.Symbol('c4')
c5 = sym.Symbol('c5')
c6 = sym.Symbol('c6')
c7 = sym.Symbol('c7')


s1 = sym.Symbol('s1')
s2 = sym.Symbol('s2')
s3 = sym.Symbol('s3')
s4 = sym.Symbol('s4')
s5 = sym.Symbol('s5')
s6 = sym.Symbol('s6')
s7 = sym.Symbol('s7')

d3 = sym.Symbol('d3')
d5 = sym.Symbol('d5')

cx1 = sym.Symbol('cx1')
cx2 = sym.Symbol('cx2')
cx3 = sym.Symbol('cx3')
cx4 = sym.Symbol('cx4')
cx5 = sym.Symbol('cx5')
cx6 = sym.Symbol('cx6')
cx7 = sym.Symbol('cx7')

cy1 = sym.Symbol('cy1')
cy2 = sym.Symbol('cy2')
cy3 = sym.Symbol('cy3')
cy4 = sym.Symbol('cy4')
cy5 = sym.Symbol('cy5')
cy6 = sym.Symbol('cy6')
cy7 = sym.Symbol('cy7')

cz1 = sym.Symbol('cz1')
cz2 = sym.Symbol('cz2')
cz3 = sym.Symbol('cz3')
cz4 = sym.Symbol('cz4')
cz5 = sym.Symbol('cz5')
cz6 = sym.Symbol('cz6')
cz7 = sym.Symbol('cz7')

g = sym.Symbol('g')

In [ ]:
teta=np.array([[0,0,0],[0,0,t1],[0,0,t2],[0,0,t3],[0,0,t4],[0,0,t5],[0,0,t6],[0,0,t7]])[:,:,np.newaxis]
tetadot=np.array([[0,0,0],[0,0,td1],[0,0,td2],[0,0,td3],[0,0,td4],[0,0,td5],[0,0,td6],[0,0,td7]])[:,:,np.newaxis]
tetadoubledot=np.array([[0,0,0],[0,0,tdd1],[0,0,tdd2],[0,0,tdd3],[0,0,tdd4],[0,0,tdd5],[0,0,tdd6],[0,0,tdd7]])[:,:,np.newaxis]
w=0*tetadoubledot
wdot=0*tetadoubledot
wdot1=0*tetadoubledot
v=0*tetadoubledot
vdot=0*tetadoubledot
vc=0*tetadoubledot

f=0*tetadoubledot
n=0*tetadoubledot

w[0]=np.array([0,0,0])[:,np.newaxis]
v[0]=np.array([0,0,0])[:,np.newaxis]
wdot[0]=np.array([0,0,0])[:,np.newaxis]
wdot1[0]=np.array([0,0,0])[:,np.newaxis]
vdot[0]=np.array([0,0,g])[:,np.newaxis]

In [ ]:
R=np.array([np.eye(3),[[c1,-s1,0],[s1,c1,0],[0,0,1]],[[c2,-s2,0],[0,0,-1],[s2,c2,0]],[[c3,-s3,0],[0,0,1],[-s3,-c3,0]],[[c4,-s4,0],[0,0,1],[-s4,-c4,0]],[[c5,-s5,0],[0,0,-1],[s5,c5,0]],[[c6,-s6,0],[0,0,-1],[s6,c6,0]],[[c7,-s7,0],[0,0,1],[-s7,-c7,0]]])
print(R.shape)


(8, 3, 3)


In [ ]:
P1=np.array([[[0],[0],[0]],[[0],[0],[0]],[[0],[0],[0]],[[0],[0],[d3]],[[0],[0],[0]],[[0],[0],[-d5]],[[0],[0],[0]],[[0],[0],[0]]])
P=np.array([[[0],[0],[0]],[[cx1],[cy1],[cz1]],[[cx2],[cy2],[cz2]],[[cx3],[cy3],[cz3]],[[cx4],[cy4],[cz4]],[[cx5],[cy5],[cz5]],[[cx6],[cy6],[cz6]],[[cx7],[cy7],[cz7]]])

print(P1.shape)

(8, 3, 1)


In [ ]:
for i in range(7):
  w[i+1]=np.dot(R[i+1].T,w[i])+tetadot[i+1]
  wdot[i+1]=np.dot(R[i+1].T,wdot[i])+np.cross(np.dot(R[i+1].T,w[i]).T,tetadot[i+1].T).T+tetadoubledot[i+1]
  #v[i+1]=np.dot(R[i+1],np.cross(w[i].T,P[i+1].T).T+v[i])
  vdot[i+1]=np.dot(R[i+1].T,vdot[i]+np.cross(wdot[i].T,P1[i+1].T).T+np.cross(w[i].T,np.cross(w[i].T,P1[i+1].T)).T)
  vc[i+1]=np.cross(wdot[i+1].T,P[i+1].T).T+np.cross(w[i+1].T,np.cross(w[i+1].T,P[i+1].T)).T+vdot[i+1]
#print('v',v)
print('w',w)
print('vdot',vdot)
print('wdot',wdot)
print('vci',vc)

w [[[0]
  [0]
  [0]]

 [[0]
  [0]
  [td1]]

 [[s2*td1]
  [c2*td1]
  [td2]]

 [[c3*s2*td1 - s3*td2]
  [-c3*td2 - s2*s3*td1]
  [c2*td1 + td3]]

 [[c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3)]
  [-c4*(c2*td1 + td3) - s4*(c3*s2*td1 - s3*td2)]
  [-c3*td2 - s2*s3*td1 + td4]]

 [[c5*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3)) + s5*(-c3*td2 - s2*s3*td1 + td4)]
  [c5*(-c3*td2 - s2*s3*td1 + td4) - s5*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3))]
  [c4*(c2*td1 + td3) + s4*(c3*s2*td1 - s3*td2) + td5]]

 [[c6*(c5*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3)) + s5*(-c3*td2 - s2*s3*td1 + td4)) + s6*(c4*(c2*td1 + td3) + s4*(c3*s2*td1 - s3*td2) + td5)]
  [c6*(c4*(c2*td1 + td3) + s4*(c3*s2*td1 - s3*td2) + td5) - s6*(c5*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3)) + s5*(-c3*td2 - s2*s3*td1 + td4))]
  [-c5*(-c3*td2 - s2*s3*td1 + td4) + s5*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3)) + td6]]

 [[c7*(c6*(c5*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3)) + s5*(-c3*td2 - s2*s3*td1 + td4)) + s6*(c4*(c2*td1

In [ ]:
Ixx1 = sym.Symbol('Ixx1')
Ixx2 = sym.Symbol('Ixx2')
Ixx3 = sym.Symbol('Ixx3')
Ixx4 = sym.Symbol('Ixx4')
Ixx5 = sym.Symbol('Ixx5')
Ixx6 = sym.Symbol('Ixx6')
Ixx7 = sym.Symbol('Ixx7')

Iyy1 = sym.Symbol('Iyy1')
Iyy2 = sym.Symbol('Iyy2')
Iyy3 = sym.Symbol('Iyy3')
Iyy4 = sym.Symbol('Iyy4')
Iyy5 = sym.Symbol('Iyy5')
Iyy6 = sym.Symbol('Iyy6')
Iyy7 = sym.Symbol('Iyy7')

Izz1 = sym.Symbol('Izz1')
Izz2 = sym.Symbol('Izz2')
Izz3 = sym.Symbol('Izz3')
Izz4 = sym.Symbol('Izz4')
Izz5 = sym.Symbol('Izz5')
Izz6 = sym.Symbol('Izz6')
Izz7 = sym.Symbol('Izz7')

Ixy1 = sym.Symbol('Ixy1')
Ixy2 = sym.Symbol('Ixy2')
Ixy3 = sym.Symbol('Ixy3')
Ixy4 = sym.Symbol('Ixy4')
Ixy5 = sym.Symbol('Ixy5')
Ixy6 = sym.Symbol('Ixy6')
Ixy7 = sym.Symbol('Ixy7')

Iyz1 = sym.Symbol('Iyz1')
Iyz2 = sym.Symbol('Iyz2')
Iyz3 = sym.Symbol('Iyz3')
Iyz4 = sym.Symbol('Iyz4')
Iyz5 = sym.Symbol('Iyz5')
Iyz6 = sym.Symbol('Iyz6')
Iyz7 = sym.Symbol('Iyz7')

Ixz1 = sym.Symbol('Ixz1')
Ixz2 = sym.Symbol('Ixz2')
Ixz3 = sym.Symbol('Ixz3')
Ixz4 = sym.Symbol('Ixz4')
Ixz5 = sym.Symbol('Ixz5')
Ixz6 = sym.Symbol('Ixz6')
Ixz7 = sym.Symbol('Ixz7')





m1 = sym.Symbol('m1')
m2 = sym.Symbol('m2')
m3 = sym.Symbol('m3')
m4 = sym.Symbol('m4')
m5 = sym.Symbol('m5')
m6 = sym.Symbol('m6')
m7 = sym.Symbol('m7')


I1=np.array([[Ixx1,-Ixy1,-Ixz1],[-Ixy1,Iyy1,-Iyz1],[-Ixz1,-Iyz1,Izz1]])
I2=np.array([[Ixx2,-Ixy2,-Ixz2],[-Ixy2,Iyy2,-Iyz2],[-Ixz2,-Iyz2,Izz2]])
I3=np.array([[Ixx3,-Ixy3,-Ixz3],[-Ixy3,Iyy3,-Iyz3],[-Ixz3,-Iyz3,Izz3]])
I4=np.array([[Ixx4,-Ixy4,-Ixz4],[-Ixy4,Iyy4,-Iyz4],[-Ixz4,-Iyz4,Izz4]])
I5=np.array([[Ixx5,-Ixy5,-Ixz5],[-Ixy5,Iyy5,-Iyz5],[-Ixz5,-Iyz5,Izz5]])
I6=np.array([[Ixx6,-Ixy6,-Ixz6],[-Ixy6,Iyy6,-Iyz6],[-Ixz6,-Iyz6,Izz6]])
I7=np.array([[Ixx7,-Ixy7,-Ixz7],[-Ixy7,Iyy7,-Iyz7],[-Ixz7,-Iyz7,Izz7]])

I=np.array([np.eye(3),I1,I2,I3,I4,I5,I6,I7])
M=np.array([m1,m2,m3,m4,m5,m6,m7])

In [ ]:
for i in range(7):
  f[i]=M[i]*vc[i+1]
  n[i]=np.dot(I[i+1],wdot[i+1])+np.cross(w[i+1].T,np.dot(I[i+1],w[i+1]).T).T

In [ ]:
force=0*tetadoubledot
torque=0*tetadoubledot
for i in range(6,0,-1):
  force[i]=np.dot(R[i+1],force[i+1])+f[i]
  torque[i]=n[i]+np.dot(R[i+1],torque[i+1])+np.cross(P[i].T,f[i].T).T+np.cross(P1[i].T,np.dot(R[i+1],force[i+1]).T).T
print(force)
print(torque)

[[[0]
  [0]
  [0]]

 [[c2*(c3*(c4*(c5*(c6*m7*(c7*(c6*(c5*(c4*(c3*(d3*s2*td1*td2 + d3*(c2*tdd1 - s2*td1*td2) + g*s2) - s3*(-c2**2*d3*td1**2 - d3*s2**2*td1**2)) - d5*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3))*(-c3*td2 - s2*s3*td1 + td4) - d5*(-c4*(c2*tdd1 - s2*td1*td2 + tdd3) - s4*(c3*(c2*td1*td2 + s2*tdd1) - s3*tdd2 + td3*(-c3*td2 - s2*s3*td1)) - td4*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3))) - s4*(c2*d3*td1*td2 + c2*g - d3*(c2*td1*td2 + s2*tdd1))) + s5*(-c3*(-c2**2*d3*td1**2 - d3*s2**2*td1**2) + d5*(-c4*(c2*td1 + td3) - s4*(c3*s2*td1 - s3*td2))**2 + d5*(c4*(c3*s2*td1 - s3*td2) - s4*(c2*td1 + td3))**2 - s3*(d3*s2*td1*td2 + d3*(c2*tdd1 - s2*td1*td2) + g*s2))) + s6*(c4*(c2*d3*td1*td2 + c2*g - d3*(c2*td1*td2 + s2*tdd1)) + d5*(-c4*(c2*td1 + td3) - s4*(c3*s2*td1 - s3*td2))*(-c3*td2 - s2*s3*td1 + td4) - d5*(c4*(c3*(c2*td1*td2 + s2*tdd1) - s3*tdd2 + td3*(-c3*td2 - s2*s3*td1)) - s4*(c2*tdd1 - s2*td1*td2 + tdd3) + td4*(-c4*(c2*td1 + td3) - s4*(c3*s2*td1 - s3*td2))) + s4*(c3*(d3*s2*td1*td2

2R TEST

In [ ]:
l1 = sym.Symbol('l1')
l2 = sym.Symbol('l2')
P1=np.array([[[0],[0],[0]],[[l1],[0],[0]],[[l2],[0],[0]]])
R=np.array([np.eye(3),[[c1,-s1,0],[s1,c1,0],[0,0,1]],[[c2,-s2,0],[s2,c2,0],[0,0,1]]])
for a in range(len(R)):
  P[a]=P1[a]
teta=np.array([[0,0,0],[0,0,t1],[0,0,t2]])[:,:,np.newaxis]
tetadot=np.array([[0,0,0],[0,0,td1],[0,0,td2]])[:,:,np.newaxis]
tetadoubledot=np.array([[0,0,0],[0,0,tdd1],[0,0,tdd2]])[:,:,np.newaxis]
w=0*tetadoubledot
wdot=0*tetadoubledot
wdot1=0*tetadoubledot
v=0*tetadoubledot
vdot=0*tetadoubledot
vc=0*tetadoubledot
i=0
f=0*tetadoubledot
n=0*tetadoubledot
force=0*tetadoubledot
torque=0*tetadoubledot
w[0]=np.array([0,0,0])[:,np.newaxis]
v[0]=np.array([0,0,0])[:,np.newaxis]
wdot[0]=np.array([0,0,0])[:,np.newaxis]
wdot1[0]=np.array([0,0,0])[:,np.newaxis]
vdot[0]=[[0],[g],[0]]
for i in range(2):
  w[i+1]=np.dot(R[i+1].T,w[i])+tetadot[i+1]
  wdot[i+1]=np.dot(R[i+1].T,wdot[i])+np.cross(np.dot(R[i+1].T,w[i]).T,tetadot[i+1].T).T+tetadoubledot[i+1]
  vdot[i+1]=np.dot(R[i+1].T,vdot[i]+np.cross(wdot[i].T,P[i].T).T+np.cross(w[i].T,np.cross(w[i].T,P[i].T)).T)
  vc[i+1]=np.cross(wdot[i+1].T,P1[i+1].T).T+np.cross(w[i+1].T,np.cross(w[i+1].T,P1[i+1].T)).T+vdot[i+1]
print('w',w)
print('wdot',wdot)
print('vdot',vdot)
print('vci',vc)
I=np.zeros((2,3,3))
M=np.array([m1,m2,0])
for i in range(2):
  f[i+1]=M[i]*vc[i+1]
  n[i+1]=np.dot(I[i],wdot[i+1])+np.cross(w[i+1].T,np.dot(I[i],w[i+1]).T).T



print('f',f)
print('n',n)
for i in range(2,0,-1):
  #print('R',i+1,R[i+1])
  force[i-1]=np.dot(R[i],force[i])+f[i]
  torque[i-1]=n[i]+np.dot(R[i],torque[i])+np.cross(P1[i].T,f[i].T).T+np.cross(P[i].T,np.dot(R[i],force[i]).T).T
print('force',force)
print('torque',torque)

w [[[0]
  [0]
  [0]]

 [[0]
  [0]
  [td1]]

 [[0]
  [0]
  [td1 + td2]]]
wdot [[[0]
  [0]
  [0]]

 [[0]
  [0]
  [tdd1]]

 [[0]
  [0]
  [tdd1 + tdd2]]]
vdot [[[0]
  [g]
  [0]]

 [[g*s1]
  [c1*g]
  [0]]

 [[c2*(g*s1 - l1*td1**2) + s2*(c1*g + l1*tdd1)]
  [c2*(c1*g + l1*tdd1) - s2*(g*s1 - l1*td1**2)]
  [0]]]
vci [[[0]
  [0]
  [0]]

 [[g*s1 - l1*td1**2]
  [c1*g + l1*tdd1]
  [0]]

 [[c2*(g*s1 - l1*td1**2) - l2*(td1 + td2)**2 + s2*(c1*g + l1*tdd1)]
  [c2*(c1*g + l1*tdd1) + l2*(tdd1 + tdd2) - s2*(g*s1 - l1*td1**2)]
  [0]]]
f [[[0]
  [0]
  [0]]

 [[m1*(g*s1 - l1*td1**2)]
  [m1*(c1*g + l1*tdd1)]
  [0]]

 [[m2*(c2*(g*s1 - l1*td1**2) - l2*(td1 + td2)**2 + s2*(c1*g + l1*tdd1))]
  [m2*(c2*(c1*g + l1*tdd1) + l2*(tdd1 + tdd2) - s2*(g*s1 - l1*td1**2))]
  [0]]]
n [[[0]
  [0]
  [0]]

 [[0]
  [0]
  [0]]

 [[0]
  [0]
  [0]]]
force [[[c1*m2*(c2*(g*s1 - l1*td1**2) - l2*(td1 + td2)**2 + s2*(c1*g + l1*tdd1)) + m1*(g*s1 - l1*td1**2) - m2*s1*(c2*(c1*g + l1*tdd1) + l2*(tdd1 + tdd2) - s2*(g*s1 - l1*td1**2))]
  [c1*